name: "🐞 Bug Report - Dev Edition"
description: "Report a bug if something isn't working as expected in the Elementor development versions"
title: "🐞 Bug report: "
labels: ["bug", "product/developer-edition"]
body:
  - type: markdown
    attributes:
      value: |
        ## BEFORE POSTING YOUR ISSUE

        - Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

        - If you have questions or need general support, please use:  https://wordpress.org/support/plugin/elementor

        - For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

        - To read more about Elementor, check out our documentation: https://elementor.com/help/

        - Developers docs are located at https://developers.elementor.com/

        ### Guidelines

        - Search this repository (top of the page) for the issue, and make sure it has not been fixed or reported before.

        - Make sure you are using the most updated versions of Elementor, WordPress & your theme.

        - Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

        - Change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/) (or other default WordPress theme).

        - If you're requesting a new feature, explain why you'd like it to be added in [the dedicated form](https://github.com/elementor/elementor/issues/new?assignees=&labels=&template=feature_request.yaml) and not in the bug report one.

        ## The Issue
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      options:
        - label: "I have searched for similar issues in both open and closed tickets and cannot find a duplicate."
          required: true
        - label: "The issue still exists against the latest development version of Elementor."
          required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Description"
      description: "Describe which problem you've encountered. What caused the issue, and what did you expect to happen. Attach screenshots and related links to help us understand the issue in more detail.
      Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action."
      placeholder: "When I ..."
  - type: textarea
    id: steps_to_reproduce
    validations:
      required: true
    attributes:
      label: "Steps to reproduce"
      description: "For bug reports, list all the steps needed to reproduce your issue, so we can replicate it ourselves."
      placeholder: "Verify that ..."
  - type: checkboxes
    id: isolating_the_problem
    attributes:
      label: "Isolating the problem"
      options:
        - label: "This bug happens with only Elementor plugin active (and Elementor Pro) with development versions."
        - label: "This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/))."
        - label: "I can reproduce this bug consistently using the steps above."
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: textarea
    id: system_info
    validations:
      required: true
    attributes:
      label: "System Info"
      description: "For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in https://pastebin.com/"
