name: Lint

on: [push, pull_request]

jobs:
  file-diff:
    runs-on: ubuntu-18.04
    name: Lint - File Diff
    if: startsWith( github.repository, 'elementor/' )
    outputs:
      js_diff: ${{ steps.js_diff_files.outputs.diff }}
      php_diff: ${{ steps.php_diff_files.outputs.diff }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Check JS files diff
        id: js_diff_files
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*.+(js|ts|json|jsx|tsx)
      - name: Check PHP files diff
        id: php_diff_files
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*.php


  JS-Lint:
    runs-on: ubuntu-18.04
    needs: [ 'file-diff' ]
    if: ${{ needs.file-diff.outputs.js_diff || github.ref == 'refs/heads/developer-edition' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm i
      - name: Run Lint
        run: ./node_modules/eslint/bin/eslint.js .

  PHP-Lint:
    runs-on: ubuntu-18.04
    needs: [ 'file-diff' ]
    if: ${{ needs.file-diff.outputs.php_diff || github.ref == 'refs/heads/developer-edition' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@9882bed06691b3a085010c1602ce43ef18f15c5b # v2
        with:
          php-version: '7.4'
      - name: Install Dependencies
        run: |
          composer install
          composer require php-parallel-lint/php-parallel-lint
      - name: Run Lint
        run: |
          vendor/bin/phpcs -p -s -n . --standard=./phpcs.xml --extensions=php
      - name: Run PHP Syntax Lint
        run: |
          export PATH=$HOME/.composer/vendor/bin:$PATH
          php7.2 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
          php7.3 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
          php7.4 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
          php8.0 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
          php8.1 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
      - name: Setup PHP 5.6 # not included in ubuntu 18.04
        uses: shivammathur/setup-php@9882bed06691b3a085010c1602ce43ef18f15c5b # v2
        with:
          php-version: '5.6'
          tools: composer:v2.2.0 # composer 2.3+ is not supporting php 5.6
      - name: Run PHP Syntax Lint 5.6
        run: | # remove unsupported packages PHP < 7.4
          export PATH=$HOME/.composer/vendor/bin:$PATH
          php -v
          composer remove --dev thor-juhasz/phpunit-coverage-check --ignore-platform-reqs
          composer update --no-interaction
          php vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
      - name: Setup PHP 7.1 # not included in ubuntu 18.04
        uses: shivammathur/setup-php@9882bed06691b3a085010c1602ce43ef18f15c5b # v2
        with:
          php-version: '7.1'
      - name: Run PHP Syntax Lint 7.1
        run: |
          export PATH=$HOME/.composer/vendor/bin:$PATH
          php -v
          php vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
