name: PHPUnit

on: [push, pull_request]

jobs:
  file-diff:
    runs-on: ubuntu-20.04
    name: File Diff
    if: startsWith( github.repository, 'elementor/' )
    outputs:
      php_diff: ${{ steps.php_diff_files.outputs.diff }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Check PHP files diff
        id: php_diff_files
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*.php

  test:
    runs-on: ubuntu-18.04 # It is ubuntu 18 because there are some issues with the mysql version and php 7 and 5.6.
    needs: [ 'file-diff' ]
    if: ${{ needs.file-diff.outputs.php_diff || github.ref == 'refs/heads/developer-edition' }}
    strategy:
      fail-fast: false
      matrix:
        wordpress_versions: ['latest', '5.8', '5.7']
        php_versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    name: PHPUnit - WordPress ${{ matrix.wordpress_versions }} - PHP version ${{ matrix.php_versions }}
    env:
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
    steps:
      - name: Startup MySQL service
        run: sudo /etc/init.d/mysql start
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}
      - name: Install Dependencies
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress_versions }}
      - name: Run Tests with Coverage (latest PHP & WP)
        if: ${{ matrix.php_versions >= 7.4 && matrix.wordpress_versions == 'latest' }}
        run: |
          composer update --no-interaction
          composer run coverage
      - name: Run Tests without Coverage
        if: ${{ ! ( matrix.php_versions >= 7.4 && matrix.wordpress_versions == 'latest' ) }}
        run: | # remove unsupported packages PHP < 7.4
          composer remove --dev thor-juhasz/phpunit-coverage-check --ignore-platform-reqs
          composer update --no-interaction
          composer run test
      - name: Run Test - Multisite
        run: |
          WP_MULTISITE=1
          composer update --no-interaction
          composer run test

  test-result:
    needs: test
    if: ${{ always() }} # Will be run even if 'test' matrix will be skipped
    runs-on: ubuntu-20.04
    name: PHPUnit - Test Results
    steps:
      - name: Test status
        run: echo "Test status is - ${{ needs.test.result }}"
      - name: Check test matrix status
        if: ${{ needs.test.result != 'success' && needs.test.result != 'skipped' }}
        run: exit 1
